"""
Fallback LLM implementation for testing without OpenAI API key.
"""
from typing import Dict, Any


class MockLLM:
    """Simple mock LLM that returns canned responses for demo/testing."""
    
    def __init__(self):
        self.responses = {
            "apple": "Apple Inc. is a technology company known for products like iPhone, Mac, iPad, and services including Apple Music and iCloud.",
            "revenue": "Revenue is the total amount of income generated by a company from its business operations.",
            "financial": "Financial data includes metrics like revenue, profit, margins, and other key performance indicators (KPIs).",
            "policy": "Financial policy refers to decisions made by an organization about how to manage its money and investments.",
            "quarter": "A quarter (Q1-Q4) represents a 3-month period used for financial reporting.",
            "default": "This is a demo response from the mock LLM. To enable full AI functionality, provide a valid OpenAI API key in the .env file.",
        }
    
    def invoke(self, prompt: str) -> Dict[str, Any]:
        """Simple keyword matching to return appropriate response."""
        prompt_lower = prompt.lower()
        
        for key, response in self.responses.items():
            if key in prompt_lower:
                return {"content": response}
        
        return {"content": self.responses["default"]}
    
    @property
    def content(self) -> str:
        return ""


def get_mock_llm() -> MockLLM:
    """Factory function for mock LLM."""
    return MockLLM()
